# -*- coding: utf-8 -*-

from typing import Dict, List

# If id <> number indicates an alternate form of the Pokémon.
# https://www.pokemon.com/es/pokedex/, https://bulbagarden.net/
KANTO = [
    {'id': '1', 'name': 'Bulbasaur', 'number': '1'},
    {'id': '2', 'name': 'Ivysaur', 'number': '2'},
    {'id': '3', 'name': 'Venusaur', 'number': '3'},
    {'id': '4', 'name': 'Charmander', 'number': '4'},
    {'id': '5', 'name': 'Charmeleon', 'number': '5'},
    {'id': '6', 'name': 'Charizard', 'number': '6'},
    {'id': '7', 'name': 'Squirtle', 'number': '7'},
    {'id': '8', 'name': 'Wartortle', 'number': '8'},
    {'id': '9', 'name': 'Blastoise', 'number': '9'},
    {'id': '10', 'name': 'Caterpie', 'number': '10'},
    {'id': '11', 'name': 'Metapod', 'number': '11'},
    {'id': '12', 'name': 'Butterfree', 'number': '12'},
    {'id': '13', 'name': 'Weedle', 'number': '13'},
    {'id': '14', 'name': 'Kakuna', 'number': '14'},
    {'id': '15', 'name': 'Beedrill', 'number': '15'},
    {'id': '16', 'name': 'Pidgey', 'number': '16'},
    {'id': '17', 'name': 'Pidgeotto', 'number': '17'},
    {'id': '18', 'name': 'Pidgeot', 'number': '18'},
    {'id': '19', 'name': 'Rattata', 'number': '19'},
    {'id': '20', 'name': 'Raticate', 'number': '20'},
    {'id': '21', 'name': 'Spearow', 'number': '21'},
    {'id': '22', 'name': 'Fearow', 'number': '22'},
    {'id': '23', 'name': 'Ekans', 'number': '23'},
    {'id': '24', 'name': 'Arbok', 'number': '24'},
    {'id': '25', 'name': 'Pikachu', 'number': '25'},
    {'id': '26', 'name': 'Raichu', 'number': '26'},
    {'id': '27', 'name': 'Sandshrew', 'number': '27'},
    {'id': '28', 'name': 'Sandslash', 'number': '28'},
    {'id': '29', 'name': 'Nidoran♀', 'number': '29'},
    {'id': '30', 'name': 'Nidorina', 'number': '30'},
    {'id': '31', 'name': 'Nidoqueen', 'number': '31'},
    {'id': '32', 'name': 'Nidoran♂', 'number': '32'},
    {'id': '33', 'name': 'Nidorino', 'number': '33'},
    {'id': '34', 'name': 'Nidoking', 'number': '34'},
    {'id': '35', 'name': 'Clefairy', 'number': '35'},
    {'id': '36', 'name': 'Clefable', 'number': '36'},
    {'id': '37', 'name': 'Vulpix', 'number': '37'},
    {'id': '38', 'name': 'Ninetales', 'number': '38'},
    {'id': '39', 'name': 'Jigglypuff', 'number': '39'},
    {'id': '40', 'name': 'Wigglytuff', 'number': '40'},
    {'id': '41', 'name': 'Zubat', 'number': '41'},
    {'id': '42', 'name': 'Golbat', 'number': '42'},
    {'id': '43', 'name': 'Oddish', 'number': '43'},
    {'id': '44', 'name': 'Gloom', 'number': '44'},
    {'id': '45', 'name': 'Vileplume', 'number': '45'},
    {'id': '46', 'name': 'Paras', 'number': '46'},
    {'id': '47', 'name': 'Parasect', 'number': '47'},
    {'id': '48', 'name': 'Venonat', 'number': '48'},
    {'id': '49', 'name': 'Venomoth', 'number': '49'},
    {'id': '50', 'name': 'Diglett', 'number': '50'},
    {'id': '51', 'name': 'Dugtrio', 'number': '51'},
    {'id': '52', 'name': 'Meowth', 'number': '52'},
    {'id': '53', 'name': 'Persian', 'number': '53'},
    {'id': '54', 'name': 'Psyduck', 'number': '54'},
    {'id': '55', 'name': 'Golduck', 'number': '55'},
    {'id': '56', 'name': 'Mankey', 'number': '56'},
    {'id': '57', 'name': 'Primeape', 'number': '57'},
    {'id': '58', 'name': 'Growlithe', 'number': '58'},
    {'id': '59', 'name': 'Arcanine', 'number': '59'},
    {'id': '60', 'name': 'Poliwag', 'number': '60'},
    {'id': '61', 'name': 'Poliwhirl', 'number': '61'},
    {'id': '62', 'name': 'Poliwrath', 'number': '62'},
    {'id': '63', 'name': 'Abra', 'number': '63'},
    {'id': '64', 'name': 'Kadabra', 'number': '64'},
    {'id': '65', 'name': 'Alakazam', 'number': '65'},
    {'id': '66', 'name': 'Machop', 'number': '66'},
    {'id': '67', 'name': 'Machoke', 'number': '67'},
    {'id': '68', 'name': 'Machamp', 'number': '68'},
    {'id': '69', 'name': 'Bellsprout', 'number': '69'},
    {'id': '70', 'name': 'Weepinbell', 'number': '70'},
    {'id': '71', 'name': 'Victreebel', 'number': '71'},
    {'id': '72', 'name': 'Tentacool', 'number': '72'},
    {'id': '73', 'name': 'Tentacruel', 'number': '73'},
    {'id': '74', 'name': 'Geodude', 'number': '74'},
    {'id': '75', 'name': 'Graveler', 'number': '75'},
    {'id': '76', 'name': 'Golem', 'number': '76'},
    {'id': '77', 'name': 'Ponyta', 'number': '77'},
    {'id': '78', 'name': 'Rapidash', 'number': '78'},
    {'id': '79', 'name': 'Slowpoke', 'number': '79'},
    {'id': '80', 'name': 'Slowbro', 'number': '80'},
    {'id': '81', 'name': 'Magnemite', 'number': '81'},
    {'id': '82', 'name': 'Magneton', 'number': '82'},
    {'id': '83', 'name': "Farfetch'd", 'number': '83'},
    {'id': '84', 'name': 'Doduo', 'number': '84'},
    {'id': '85', 'name': 'Dodrio', 'number': '85'},
    {'id': '86', 'name': 'Seel', 'number': '86'},
    {'id': '87', 'name': 'Dewgong', 'number': '87'},
    {'id': '88', 'name': 'Grimer', 'number': '88'},
    {'id': '89', 'name': 'Muk', 'number': '89'},
    {'id': '90', 'name': 'Shellder', 'number': '90'},
    {'id': '91', 'name': 'Cloyster', 'number': '91'},
    {'id': '92', 'name': 'Gastly', 'number': '92'},
    {'id': '93', 'name': 'Haunter', 'number': '93'},
    {'id': '94', 'name': 'Gengar', 'number': '94'},
    {'id': '95', 'name': 'Onix', 'number': '95'},
    {'id': '96', 'name': 'Drowzee', 'number': '96'},
    {'id': '97', 'name': 'Hypno', 'number': '97'},
    {'id': '98', 'name': 'Krabby', 'number': '98'},
    {'id': '99', 'name': 'Kingler', 'number': '99'},
    {'id': '100', 'name': 'Voltorb', 'number': '100'},
    {'id': '101', 'name': 'Electrode', 'number': '101'},
    {'id': '102', 'name': 'Exeggcute', 'number': '102'},
    {'id': '103', 'name': 'Exeggutor', 'number': '103'},
    {'id': '104', 'name': 'Cubone', 'number': '104'},
    {'id': '105', 'name': 'Marowak', 'number': '105'},
    {'id': '106', 'name': 'Hitmonlee', 'number': '106'},
    {'id': '107', 'name': 'Hitmonchan', 'number': '107'},
    {'id': '108', 'name': 'Lickitung', 'number': '108'},
    {'id': '109', 'name': 'Koffing', 'number': '109'},
    {'id': '110', 'name': 'Weezing', 'number': '110'},
    {'id': '111', 'name': 'Rhyhorn', 'number': '111'},
    {'id': '112', 'name': 'Rhydon', 'number': '112'},
    {'id': '113', 'name': 'Chansey', 'number': '113'},
    {'id': '114', 'name': 'Tangela', 'number': '114'},
    {'id': '115', 'name': 'Kangaskhan', 'number': '115'},
    {'id': '116', 'name': 'Horsea', 'number': '116'},
    {'id': '117', 'name': 'Seadra', 'number': '117'},
    {'id': '118', 'name': 'Goldeen', 'number': '118'},
    {'id': '119', 'name': 'Seaking', 'number': '119'},
    {'id': '120', 'name': 'Staryu', 'number': '120'},
    {'id': '121', 'name': 'Starmie', 'number': '121'},
    {'id': '122', 'name': 'Mr. Mime', 'number': '122'},
    {'id': '123', 'name': 'Scyther', 'number': '123'},
    {'id': '124', 'name': 'Jynx', 'number': '124'},
    {'id': '125', 'name': 'Electabuzz', 'number': '125'},
    {'id': '126', 'name': 'Magmar', 'number': '126'},
    {'id': '127', 'name': 'Pinsir', 'number': '127'},
    {'id': '128', 'name': 'Tauros', 'number': '128'},
    {'id': '129', 'name': 'Magikarp', 'number': '129'},
    {'id': '130', 'name': 'Gyarados', 'number': '130'},
    {'id': '131', 'name': 'Lapras', 'number': '131'},
    {'id': '131', 'name': 'Ditto', 'number': '131'},
    {'id': '131', 'name': 'Eevee', 'number': '131'},
    {'id': '131', 'name': 'Vaporeon', 'number': '131'},
    {'id': '131', 'name': 'Jolteon', 'number': '131'},
    {'id': '131', 'name': 'Flareon', 'number': '131'},
    {'id': '131', 'name': 'Porygon', 'number': '131'},
    {'id': '131', 'name': 'Omanyte', 'number': '131'},
    {'id': '131', 'name': 'Omastar', 'number': '131'},
    {'id': '140', 'name': 'Kabuto', 'number': '140'},
    {'id': '141', 'name': 'Kabutops', 'number': '141'},
    {'id': '142', 'name': 'Aerodactyl', 'number': '142'},
    {'id': '143', 'name': 'Snorlax', 'number': '143'},
    {'id': '144', 'name': 'Articuno', 'number': '144'},
    {'id': '145', 'name': 'Zapdos', 'number': '145'},
    {'id': '146', 'name': 'Moltres', 'number': '146'},
    {'id': '147', 'name': 'Dratini', 'number': '147'},
    {'id': '148', 'name': 'Dragonair', 'number': '148'},
    {'id': '149', 'name': 'Dragonite', 'number': '149'},
    {'id': '150', 'name': 'Mewtwo', 'number': '150'},
    {'id': 'mewtwo-armor', 'name': 'Armored Mewtwo', 'number': '150'},
    {'id': '151', 'name': 'Mew', 'number': '151'},
]

JOHTO = [
    {'id': '152', 'name': 'Chikorita', 'number': '152'},
    {'id': '153', 'name': 'Bayleef', 'number': '153'},
    {'id': '154', 'name': 'Meganium', 'number': '154'},
    {'id': '155', 'name': 'Cyndaquil', 'number': '155'},
    {'id': '156', 'name': 'Quilava', 'number': '156'},
    {'id': '157', 'name': 'Typhlosion', 'number': '157'},
    {'id': '158', 'name': 'Totodile', 'number': '158'},
    {'id': '159', 'name': 'Croconaw', 'number': '159'},
    {'id': '160', 'name': 'Feraligatr', 'number': '160'},
    {'id': '161', 'name': 'Sentret', 'number': '161'},
    {'id': '162', 'name': 'Furret', 'number': '162'},
    {'id': '163', 'name': 'Hoothoot', 'number': '163'},
    {'id': '164', 'name': 'Noctowl', 'number': '164'},
    {'id': '165', 'name': 'Ledyba', 'number': '165'},
    {'id': '166', 'name': 'Ledian', 'number': '166'},
    {'id': '167', 'name': 'Spinarak', 'number': '167'},
    {'id': '168', 'name': 'Ariados', 'number': '168'},
    {'id': '169', 'name': 'Crobat', 'number': '169'},
    {'id': '170', 'name': 'Chinchou', 'number': '170'},
    {'id': '171', 'name': 'Lanturn', 'number': '171'},
    {'id': '172', 'name': 'Pichu', 'number': '172'},
    {'id': '173', 'name': 'Cleffa', 'number': '173'},
    {'id': '174', 'name': 'Igglybuff', 'number': '174'},
    {'id': '175', 'name': 'Togepi', 'number': '175'},
    {'id': '176', 'name': 'Togetic', 'number': '176'},
    {'id': '177', 'name': 'Natu', 'number': '177'},
    {'id': '178', 'name': 'Xatu', 'number': '178'},
    {'id': '179', 'name': 'Mareep', 'number': '179'},
    {'id': '180', 'name': 'Flaaffy', 'number': '180'},
    {'id': '181', 'name': 'Ampharos', 'number': '181'},
    {'id': '182', 'name': 'Bellossom', 'number': '182'},
    {'id': '183', 'name': 'Marill', 'number': '183'},
    {'id': '184', 'name': 'Azumarill', 'number': '184'},
    {'id': '185', 'name': 'Sudowoodo', 'number': '185'},
    {'id': '186', 'name': 'Politoed', 'number': '186'},
    {'id': '187', 'name': 'Hoppip', 'number': '187'},
    {'id': '188', 'name': 'Skiploom', 'number': '188'},
    {'id': '189', 'name': 'Jumpluff', 'number': '189'},
    {'id': '190', 'name': 'Aipom', 'number': '190'},
    {'id': '191', 'name': 'Sunkern', 'number': '191'},
    {'id': '192', 'name': 'Sunflora', 'number': '192'},
    {'id': '193', 'name': 'Yanma', 'number': '193'},
    {'id': '194', 'name': 'Wooper', 'number': '194'},
    {'id': '195', 'name': 'Quagsire', 'number': '195'},
    {'id': '196', 'name': 'Espeon', 'number': '196'},
    {'id': '197', 'name': 'Umbreon', 'number': '197'},
    {'id': '198', 'name': 'Murkrow', 'number': '198'},
    {'id': '199', 'name': 'Slowking', 'number': '199'},
    {'id': '200', 'name': 'Misdreavus', 'number': '200'},
    {'id': 'unown-a', 'name': 'Unown A', 'number': '201'},
    {'id': 'unown-b', 'name': 'Unown B', 'number': '201'},
    {'id': 'unown-c', 'name': 'Unown C', 'number': '201'},
    {'id': 'unown-d', 'name': 'Unown D', 'number': '201'},
    {'id': 'unown-e', 'name': 'Unown E', 'number': '201'},
    {'id': 'unown-f', 'name': 'Unown F', 'number': '201'},
    {'id': 'unown-g', 'name': 'Unown G', 'number': '201'},
    {'id': 'unown-h', 'name': 'Unown H', 'number': '201'},
    {'id': 'unown-i', 'name': 'Unown I', 'number': '201'},
    {'id': 'unown-j', 'name': 'Unown J', 'number': '201'},
    {'id': 'unown-k', 'name': 'Unown K', 'number': '201'},
    {'id': 'unown-l', 'name': 'Unown L', 'number': '201'},
    {'id': 'unown-m', 'name': 'Unown M', 'number': '201'},
    {'id': 'unown-n', 'name': 'Unown N', 'number': '201'},
    {'id': 'unown-o', 'name': 'Unown O', 'number': '201'},
    {'id': 'unown-p', 'name': 'Unown P', 'number': '201'},
    {'id': 'unown-q', 'name': 'Unown Q', 'number': '201'},
    {'id': 'unown-r', 'name': 'Unown R', 'number': '201'},
    {'id': 'unown-s', 'name': 'Unown S', 'number': '201'},
    {'id': 'unown-t', 'name': 'Unown T', 'number': '201'},
    {'id': 'unown-u', 'name': 'Unown U', 'number': '201'},
    {'id': 'unown-v', 'name': 'Unown V', 'number': '201'},
    {'id': 'unown-w', 'name': 'Unown W', 'number': '201'},
    {'id': 'unown-x', 'name': 'Unown X', 'number': '201'},
    {'id': 'unown-y', 'name': 'Unown Y', 'number': '201'},
    {'id': 'unown-z', 'name': 'Unown Z', 'number': '201'},
    {'id': '202', 'name': 'Wobbuffet', 'number': '202'},
    {'id': '203', 'name': 'Girafarig', 'number': '203'},
    {'id': '204', 'name': 'Pineco', 'number': '204'},
    {'id': '205', 'name': 'Forretress', 'number': '205'},
    {'id': '206', 'name': 'Dunsparce', 'number': '206'},
    {'id': '207', 'name': 'Gligar', 'number': '207'},
    {'id': '208', 'name': 'Steelix', 'number': '208'},
    {'id': '209', 'name': 'Snubbull', 'number': '209'},
    {'id': '210', 'name': 'Granbull', 'number': '210'},
    {'id': '211', 'name': 'Qwilfish', 'number': '211'},
    {'id': '212', 'name': 'Scizor', 'number': '212'},
    {'id': '213', 'name': 'Shuckle', 'number': '213'},
    {'id': '214', 'name': 'Heracross', 'number': '214'},
    {'id': '215', 'name': 'Sneasel', 'number': '215'},
    {'id': '216', 'name': 'Teddiursa', 'number': '216'},
    {'id': '217', 'name': 'Ursaring', 'number': '217'},
    {'id': '218', 'name': 'Slugma', 'number': '218'},
    {'id': '219', 'name': 'Magcargo', 'number': '219'},
    {'id': '220', 'name': 'Swinub', 'number': '220'},
    {'id': '221', 'name': 'Piloswine', 'number': '221'},
    {'id': '222', 'name': 'Corsola', 'number': '222'},
    {'id': '223', 'name': 'Remoraid', 'number': '223'},
    {'id': '224', 'name': 'Octillery', 'number': '224'},
    {'id': '225', 'name': 'Delibird', 'number': '225'},
    {'id': '226', 'name': 'Mantine', 'number': '226'},
    {'id': '227', 'name': 'Skarmory', 'number': '227'},
    {'id': '228', 'name': 'Houndour', 'number': '228'},
    {'id': '229', 'name': 'Houndoom', 'number': '229'},
    {'id': '230', 'name': 'Kingdra', 'number': '230'},
    {'id': '231', 'name': 'Phanpy', 'number': '231'},
    {'id': '232', 'name': 'Donphan', 'number': '232'},
    {'id': '233', 'name': 'Porygon2', 'number': '233'},
    {'id': '234', 'name': 'Stantler', 'number': '234'},
    {'id': '235', 'name': 'Smeargle', 'number': '235'},
    {'id': '236', 'name': 'Tyrogue', 'number': '236'},
    {'id': '237', 'name': 'Hitmontop', 'number': '237'},
    {'id': '238', 'name': 'Smoochum', 'number': '238'},
    {'id': '239', 'name': 'Elekid', 'number': '239'},
    {'id': '240', 'name': 'Magby', 'number': '240'},
    {'id': '241', 'name': 'Miltank', 'number': '241'},
    {'id': '242', 'name': 'Blissey', 'number': '242'},
    {'id': '243', 'name': 'Raikou', 'number': '243'},
    {'id': '244', 'name': 'Entei', 'number': '244'},
    {'id': '245', 'name': 'Suicune', 'number': '245'},
    {'id': '246', 'name': 'Larvitar', 'number': '246'},
    {'id': '247', 'name': 'Pupitar', 'number': '247'},
    {'id': '248', 'name': 'Tyranitar', 'number': '248'},
    {'id': '249', 'name': 'Lugia', 'number': '249'},
    {'id': '250', 'name': 'Ho-Oh', 'number': '250'},
    {'id': '251', 'name': 'Celebi', 'number': '251'},
]

HOENN = [
    {'id': 'unown-em', 'name': 'Unown !', 'number': '201'},
    {'id': 'unown-qm', 'name': 'Unown ?', 'number': '201'},
    {'id': '252', 'name': 'Treecko', 'number': '252'},
    {'id': '253', 'name': 'Grovyle', 'number': '253'},
    {'id': '254', 'name': 'Sceptile', 'number': '254'},
    {'id': '255', 'name': 'Torchic', 'number': '255'},
    {'id': '256', 'name': 'Combusken', 'number': '256'},
    {'id': '257', 'name': 'Blaziken', 'number': '257'},
    {'id': '258', 'name': 'Mudkip', 'number': '258'},
    {'id': '259', 'name': 'Marshtomp', 'number': '259'},
    {'id': '260', 'name': 'Swampert', 'number': '260'},
    {'id': '261', 'name': 'Poochyena', 'number': '261'},
    {'id': '262', 'name': 'Mightyena', 'number': '262'},
    {'id': '263', 'name': 'Zigzagoon', 'number': '263'},
    {'id': '264', 'name': 'Linoone', 'number': '264'},
    {'id': '265', 'name': 'Wurmple', 'number': '265'},
    {'id': '266', 'name': 'Silcoon', 'number': '266'},
    {'id': '267', 'name': 'Beautifly', 'number': '267'},
    {'id': '268', 'name': 'Cascoon', 'number': '268'},
    {'id': '269', 'name': 'Dustox', 'number': '269'},
    {'id': '270', 'name': 'Lotad', 'number': '270'},
    {'id': '271', 'name': 'Lombre', 'number': '271'},
    {'id': '272', 'name': 'Ludicolo', 'number': '272'},
    {'id': '273', 'name': 'Seedot', 'number': '273'},
    {'id': '274', 'name': 'Nuzleaf', 'number': '274'},
    {'id': '275', 'name': 'Shiftry', 'number': '275'},
    {'id': '276', 'name': 'Taillow', 'number': '276'},
    {'id': '277', 'name': 'Swellow', 'number': '277'},
    {'id': '278', 'name': 'Wingull', 'number': '278'},
    {'id': '279', 'name': 'Pelipper', 'number': '279'},
    {'id': '280', 'name': 'Ralts', 'number': '280'},
    {'id': '281', 'name': 'Kirlia', 'number': '281'},
    {'id': '282', 'name': 'Gardevoir', 'number': '282'},
    {'id': '283', 'name': 'Surskit', 'number': '283'},
    {'id': '284', 'name': 'Masquerain', 'number': '284'},
    {'id': '285', 'name': 'Shroomish', 'number': '285'},
    {'id': '286', 'name': 'Breloom', 'number': '286'},
    {'id': '287', 'name': 'Slakoth', 'number': '287'},
    {'id': '288', 'name': 'Vigoroth', 'number': '288'},
    {'id': '289', 'name': 'Slaking', 'number': '289'},
    {'id': '290', 'name': 'Nincada', 'number': '290'},
    {'id': '291', 'name': 'Ninjask', 'number': '291'},
    {'id': '292', 'name': 'Shedinja', 'number': '292'},
    {'id': '293', 'name': 'Whismur', 'number': '293'},
    {'id': '294', 'name': 'Loudred', 'number': '294'},
    {'id': '295', 'name': 'Exploud', 'number': '295'},
    {'id': '296', 'name': 'Makuhita', 'number': '296'},
    {'id': '297', 'name': 'Hariyama', 'number': '297'},
    {'id': '298', 'name': 'Azurill', 'number': '298'},
    {'id': '299', 'name': 'Nosepass', 'number': '299'},
    {'id': '300', 'name': 'Skitty', 'number': '300'},
    {'id': '301', 'name': 'Delcatty', 'number': '301'},
    {'id': '302', 'name': 'Sableye', 'number': '302'},
    {'id': '303', 'name': 'Mawile', 'number': '303'},
    {'id': '304', 'name': 'Aron', 'number': '304'},
    {'id': '305', 'name': 'Lairon', 'number': '305'},
    {'id': '306', 'name': 'Aggron', 'number': '306'},
    {'id': '307', 'name': 'Meditite', 'number': '307'},
    {'id': '308', 'name': 'Medicham', 'number': '308'},
    {'id': '309', 'name': 'Electrike', 'number': '309'},
    {'id': '310', 'name': 'Manectric', 'number': '310'},
    {'id': '311', 'name': 'Plusle', 'number': '311'},
    {'id': '312', 'name': 'Minun', 'number': '312'},
    {'id': '313', 'name': 'Volbeat', 'number': '313'},
    {'id': '314', 'name': 'Illumise', 'number': '314'},
    {'id': '315', 'name': 'Roselia', 'number': '315'},
    {'id': '316', 'name': 'Gulpin', 'number': '316'},
    {'id': '317', 'name': 'Swalot', 'number': '317'},
    {'id': '318', 'name': 'Carvanha', 'number': '318'},
    {'id': '319', 'name': 'Sharpedo', 'number': '319'},
    {'id': '320', 'name': 'Wailmer', 'number': '320'},
    {'id': '321', 'name': 'Wailord', 'number': '321'},
    {'id': '322', 'name': 'Numel', 'number': '322'},
    {'id': '323', 'name': 'Camerupt', 'number': '323'},
    {'id': '324', 'name': 'Torkoal', 'number': '324'},
    {'id': '325', 'name': 'Spoink', 'number': '325'},
    {'id': '326', 'name': 'Grumpig', 'number': '326'},
    {'id': '327', 'name': 'Spinda', 'number': '327'},
    {'id': '328', 'name': 'Trapinch', 'number': '328'},
    {'id': '329', 'name': 'Vibrava', 'number': '329'},
    {'id': '330', 'name': 'Flygon', 'number': '330'},
    {'id': '331', 'name': 'Cacnea', 'number': '331'},
    {'id': '332', 'name': 'Cacturne', 'number': '332'},
    {'id': '333', 'name': 'Swablu', 'number': '333'},
    {'id': '334', 'name': 'Altaria', 'number': '334'},
    {'id': '335', 'name': 'Zangoose', 'number': '335'},
    {'id': '336', 'name': 'Seviper', 'number': '336'},
    {'id': '337', 'name': 'Lunatone', 'number': '337'},
    {'id': '338', 'name': 'Solrock', 'number': '338'},
    {'id': '339', 'name': 'Barboach', 'number': '339'},
    {'id': '340', 'name': 'Whiscash', 'number': '340'},
    {'id': '341', 'name': 'Corphish', 'number': '341'},
    {'id': '342', 'name': 'Crawdaunt', 'number': '342'},
    {'id': '343', 'name': 'Baltoy', 'number': '343'},
    {'id': '344', 'name': 'Claydol', 'number': '344'},
    {'id': '345', 'name': 'Lileep', 'number': '345'},
    {'id': '346', 'name': 'Cradily', 'number': '346'},
    {'id': '347', 'name': 'Anorith', 'number': '347'},
    {'id': '348', 'name': 'Armaldo', 'number': '348'},
    {'id': '349', 'name': 'Feebas', 'number': '349'},
    {'id': '350', 'name': 'Milotic', 'number': '350'},
    {'id': '351', 'name': 'Normal Castform', 'number': '351'},
    {'id': 'castform-rainy', 'name': 'Rainy Castform', 'number': '351'},
    {'id': 'castform-snowy', 'name': 'Snowy Castform', 'number': '351'},
    {'id': 'castform-sunny', 'name': 'Sunny Castform', 'number': '351'},
    {'id': '352', 'name': 'Kecleon', 'number': '352'},
    {'id': '353', 'name': 'Shuppet', 'number': '353'},
    {'id': '354', 'name': 'Banette', 'number': '354'},
    {'id': '355', 'name': 'Duskull', 'number': '355'},
    {'id': '356', 'name': 'Dusclops', 'number': '356'},
    {'id': '357', 'name': 'Tropius', 'number': '357'},
    {'id': '358', 'name': 'Chimecho', 'number': '358'},
    {'id': '359', 'name': 'Absol', 'number': '359'},
    {'id': '360', 'name': 'Wynaut', 'number': '360'},
    {'id': '361', 'name': 'Snorunt', 'number': '361'},
    {'id': '362', 'name': 'Glalie', 'number': '362'},
    {'id': '363', 'name': 'Spheal', 'number': '363'},
    {'id': '364', 'name': 'Sealeo', 'number': '364'},
    {'id': '365', 'name': 'Walrein', 'number': '365'},
    {'id': '366', 'name': 'Clamperl', 'number': '366'},
    {'id': '367', 'name': 'Huntail', 'number': '367'},
    {'id': '368', 'name': 'Gorebyss', 'number': '368'},
    {'id': '369', 'name': 'Relicanth', 'number': '369'},
    {'id': '370', 'name': 'Luvdisc', 'number': '370'},
    {'id': '371', 'name': 'Bagon', 'number': '371'},
    {'id': '372', 'name': 'Shelgon', 'number': '372'},
    {'id': '373', 'name': 'Salamence', 'number': '373'},
    {'id': '374', 'name': 'Beldum', 'number': '374'},
    {'id': '375', 'name': 'Metang', 'number': '375'},
    {'id': '376', 'name': 'Metagross', 'number': '376'},
    {'id': '377', 'name': 'Regirock', 'number': '377'},
    {'id': '378', 'name': 'Regice', 'number': '378'},
    {'id': '379', 'name': 'Registeel', 'number': '379'},
    {'id': '380', 'name': 'Latias', 'number': '380'},
    {'id': '381', 'name': 'Latios', 'number': '381'},
    {'id': '382', 'name': 'Kyogre', 'number': '382'},
    {'id': '383', 'name': 'Groudon', 'number': '383'},
    {'id': '384', 'name': 'Rayquaza', 'number': '384'},
    {'id': '385', 'name': 'Jirachi', 'number': '385'},
    {'id': '386', 'name': 'Deoxys (Normal Forme)', 'number': '386'},
    {'id': 'deoxys-attack', 'name': 'Deoxys (Attack Forme)', 'number': '386'},
    {'id': 'deoxys-defense', 'name': 'Deoxys (Defense Forme)', 'number': '386'},
    {'id': 'deoxys-speed', 'name': 'Deoxys (Speed Forme)', 'number': '386'},
]

SINNOH = [
    {'id': '387', 'name': 'Turtwig', 'number': '387'},
    {'id': '388', 'name': 'Grotle', 'number': '388'},
    {'id': '389', 'name': 'Torterra', 'number': '389'},
    {'id': '390', 'name': 'Chimchar', 'number': '390'},
    {'id': '391', 'name': 'Monferno', 'number': '391'},
    {'id': '392', 'name': 'Infernape', 'number': '392'},
    {'id': '393', 'name': 'Piplup', 'number': '393'},
    {'id': '394', 'name': 'Prinplup', 'number': '394'},
    {'id': '395', 'name': 'Empoleon', 'number': '395'},
    {'id': '396', 'name': 'Starly', 'number': '396'},
    {'id': '397', 'name': 'Staravia', 'number': '397'},
    {'id': '398', 'name': 'Staraptor', 'number': '398'},
    {'id': '399', 'name': 'Bidoof', 'number': '399'},
    {'id': '400', 'name': 'Bibarel', 'number': '400'},
    {'id': '401', 'name': 'Kricketot', 'number': '401'},
    {'id': '402', 'name': 'Kricketune', 'number': '402'},
    {'id': '403', 'name': 'Shinx', 'number': '403'},
    {'id': '404', 'name': 'Luxio', 'number': '404'},
    {'id': '405', 'name': 'Luxray', 'number': '405'},
    {'id': '406', 'name': 'Budew', 'number': '406'},
    {'id': '407', 'name': 'Roserade', 'number': '407'},
    {'id': '408', 'name': 'Cranidos', 'number': '408'},
    {'id': '409', 'name': 'Rampardos', 'number': '409'},
    {'id': '410', 'name': 'Shieldon', 'number': '410'},
    {'id': '411', 'name': 'Bastiodon', 'number': '411'},
    {'id': 'burmy-plant', 'name': 'Burmy (Plant Cloak)', 'number': '412'},
    {'id': 'burmy-sandy', 'name': 'Burmy (Sandy Cloak)', 'number': '412'},
    {'id': 'burmy-trash', 'name': 'Burmy (Trash Cloak)', 'number': '412'},
    {'id': 'wormadam-plant', 'name': 'Wormadam (Plant Cloak)', 'number': '413'},
    {'id': 'wormadam-sandy', 'name': 'Wormadam (Sandy Cloak)', 'number': '413'},
    {'id': 'wormadam-trash', 'name': 'Wormadam (Trash Cloak)', 'number': '413'},
    {'id': '414', 'name': 'Mothim', 'number': '414'},
    {'id': '415', 'name': 'Combee', 'number': '415'},
    {'id': '416', 'name': 'Vespiquen', 'number': '416'},
    {'id': '417', 'name': 'Pachirisu', 'number': '417'},
    {'id': '418', 'name': 'Buizel', 'number': '418'},
    {'id': '419', 'name': 'Floatzel', 'number': '419'},
    {'id': '420', 'name': 'Cherubi', 'number': '420'},
    {'id': 'cherrim-overcast', 'name': 'Cherrim (Overcast Form)', 'number': '421'},
    {'id': 'cherrim-sunshine', 'name': 'Cherrim (Sunshine Form)', 'number': '421'},
    {'id': 'shellos-west-sea', 'name': 'Shellos (West Sea)', 'number': '422'},
    {'id': 'shellos-east-sea', 'name': 'Shellos (East Sea)', 'number': '422'},
    {'id': 'gastrodon-west-sea', 'name': 'Gastrodon (West Sea)', 'number': '423'},
    {'id': 'gastrodon-east-sea', 'name': 'Gastrodon (East Sea)', 'number': '423'},
    {'id': '424', 'name': 'Ambipom', 'number': '424'},
    {'id': '425', 'name': 'Drifloon', 'number': '425'},
    {'id': '426', 'name': 'Drifblim', 'number': '426'},
    {'id': '427', 'name': 'Buneary', 'number': '427'},
    {'id': '428', 'name': 'Lopunny', 'number': '428'},
    {'id': '429', 'name': 'Mismagius', 'number': '429'},
    {'id': '430', 'name': 'Honchkrow', 'number': '430'},
    {'id': '431', 'name': 'Glameow', 'number': '431'},
    {'id': '432', 'name': 'Purugly', 'number': '432'},
    {'id': '433', 'name': 'Chingling', 'number': '433'},
    {'id': '434', 'name': 'Stunky', 'number': '434'},
    {'id': '435', 'name': 'Skuntank', 'number': '435'},
    {'id': '436', 'name': 'Bronzor', 'number': '436'},
    {'id': '437', 'name': 'Bronzong', 'number': '437'},
    {'id': '438', 'name': 'Bonsly', 'number': '438'},
    {'id': '439', 'name': 'Mime Jr.', 'number': '439'},
    {'id': '440', 'name': 'Happiny', 'number': '440'},
    {'id': '441', 'name': 'Chatot', 'number': '441'},
    {'id': '442', 'name': 'Spiritomb', 'number': '442'},
    {'id': '443', 'name': 'Gible', 'number': '443'},
    {'id': '444', 'name': 'Gabite', 'number': '444'},
    {'id': '445', 'name': 'Garchomp', 'number': '445'},
    {'id': '446', 'name': 'Munchlax', 'number': '446'},
    {'id': '447', 'name': 'Riolu', 'number': '447'},
    {'id': '448', 'name': 'Lucario', 'number': '448'},
    {'id': '449', 'name': 'Hippopotas', 'number': '449'},
    {'id': '450', 'name': 'Hippowdon', 'number': '450'},
    {'id': '451', 'name': 'Skorupi', 'number': '451'},
    {'id': '452', 'name': 'Drapion', 'number': '452'},
    {'id': '453', 'name': 'Croagunk', 'number': '453'},
    {'id': '454', 'name': 'Toxicroak', 'number': '454'},
    {'id': '455', 'name': 'Carnivine', 'number': '455'},
    {'id': '456', 'name': 'Finneon', 'number': '456'},
    {'id': '457', 'name': 'Lumineon', 'number': '457'},
    {'id': '458', 'name': 'Mantyke', 'number': '458'},
    {'id': '459', 'name': 'Snover', 'number': '459'},
    {'id': '460', 'name': 'Abomasnow', 'number': '460'},
    {'id': '461', 'name': 'Weavile', 'number': '461'},
    {'id': '462', 'name': 'Magnezone', 'number': '462'},
    {'id': '463', 'name': 'Lickilicky', 'number': '463'},
    {'id': '464', 'name': 'Rhyperior', 'number': '464'},
    {'id': '465', 'name': 'Tangrowth', 'number': '465'},
    {'id': '466', 'name': 'Electivire', 'number': '466'},
    {'id': '467', 'name': 'Magmortar', 'number': '467'},
    {'id': '468', 'name': 'Togekiss', 'number': '468'},
    {'id': '469', 'name': 'Yanmega', 'number': '469'},
    {'id': '470', 'name': 'Leafeon', 'number': '470'},
    {'id': '471', 'name': 'Glaceon', 'number': '471'},
    {'id': '472', 'name': 'Gliscor', 'number': '472'},
    {'id': '473', 'name': 'Mamoswine', 'number': '473'},
    {'id': '474', 'name': 'Porygon-Z', 'number': '474'},
    {'id': '475', 'name': 'Gallade', 'number': '475'},
    {'id': '476', 'name': 'Probopass', 'number': '476'},
    {'id': '477', 'name': 'Dusknoir', 'number': '477'},
    {'id': '478', 'name': 'Froslass', 'number': '478'},
    {'id': '479', 'name': 'Rotom', 'number': '479'},
    {'id': 'rotom-fan', 'name': 'Fan Rotom', 'number': '479'},
    {'id': 'rotom-frost', 'name': 'Frost Rotom', 'number': '479'},
    {'id': 'rotom-heat', 'name': 'Heat Rotom', 'number': '479'},
    {'id': 'rotom-mow', 'name': 'Mow Rotom', 'number': '479'},
    {'id': 'rotom-wash', 'name': 'Wash Rotom', 'number': '479'},
    {'id': '480', 'name': 'Uxie', 'number': '480'},
    {'id': '481', 'name': 'Mesprit', 'number': '481'},
    {'id': '482', 'name': 'Azelf', 'number': '482'},
    {'id': '483', 'name': 'Dialga', 'number': '483'},
    {'id': '484', 'name': 'Palkia', 'number': '484'},
    {'id': '485', 'name': 'Heatran', 'number': '485'},
    {'id': '486', 'name': 'Regigigas', 'number': '486'},
    {'id': 'giratina-altered', 'name': 'Giratina (Altered Forme)', 'number': '487'},
    {'id': 'giratina-origin', 'name': 'Giratina (Origin Forme)', 'number': '487'},
    {'id': '488', 'name': 'Cresselia', 'number': '488'},
    {'id': '489', 'name': 'Phione', 'number': '489'},
    {'id': '490', 'name': 'Manaphy', 'number': '490'},
    {'id': '491', 'name': 'Darkrai', 'number': '491'},
    {'id': 'shaymin-land', 'name': 'Shaymin (Land Forme)', 'number': '492'},
    {'id': 'shaymin-sky', 'name': 'Shaymin (Sky Forme)', 'number': '492'},
    {'id': '493', 'name': 'Arceus', 'number': '493'},
]

UNOVA = [
    {'id': '494', 'name': 'Victini', 'number': '494'},
    {'id': '495', 'name': 'Snivy', 'number': '495'},
    {'id': '496', 'name': 'Servine', 'number': '496'},
    {'id': '497', 'name': 'Serperior', 'number': '497'},
    {'id': '498', 'name': 'Tepig', 'number': '498'},
    {'id': '499', 'name': 'Pignite', 'number': '499'},
    {'id': '500', 'name': 'Emboar', 'number': '500'},
    {'id': '501', 'name': 'Oshawott', 'number': '501'},
    {'id': '502', 'name': 'Dewott', 'number': '502'},
    {'id': '503', 'name': 'Samurott', 'number': '503'},
    {'id': '504', 'name': 'Patrat', 'number': '504'},
    {'id': '505', 'name': 'Watchog', 'number': '505'},
    {'id': '506', 'name': 'Lillipup', 'number': '506'},
    {'id': '507', 'name': 'Herdier', 'number': '507'},
    {'id': '508', 'name': 'Stoutland', 'number': '508'},
    {'id': '509', 'name': 'Purrloin', 'number': '509'},
    {'id': '510', 'name': 'Liepard', 'number': '510'},
    {'id': '511', 'name': 'Pansage', 'number': '511'},
    {'id': '512', 'name': 'Simisage', 'number': '512'},
    {'id': '513', 'name': 'Pansear', 'number': '513'},
    {'id': '514', 'name': 'Simisear', 'number': '514'},
    {'id': '515', 'name': 'Panpour', 'number': '515'},
    {'id': '516', 'name': 'Simipour', 'number': '516'},
    {'id': '517', 'name': 'Munna', 'number': '517'},
    {'id': '518', 'name': 'Musharna', 'number': '518'},
    {'id': '519', 'name': 'Pidove', 'number': '519'},
    {'id': '520', 'name': 'Tranquill', 'number': '520'},
    {'id': '521', 'name': 'Unfezant (Both)', 'number': '521'},
    {'id': 'unfezant-male', 'name': 'Unfezant (Male)', 'number': '521'},
    {'id': 'unfezant-female', 'name': 'Unfezant (Female)', 'number': '521'},
    {'id': '522', 'name': 'Blitzle', 'number': '522'},
    {'id': '523', 'name': 'Zebstrika', 'number': '523'},
    {'id': '524', 'name': 'Roggenrola', 'number': '524'},
    {'id': '525', 'name': 'Boldore', 'number': '525'},
    {'id': '526', 'name': 'Gigalith', 'number': '526'},
    {'id': '527', 'name': 'Woobat', 'number': '527'},
    {'id': '528', 'name': 'Swoobat', 'number': '528'},
    {'id': '529', 'name': 'Drilbur', 'number': '529'},
    {'id': '530', 'name': 'Excadrill', 'number': '530'},
    {'id': '531', 'name': 'Audino', 'number': '531'},
    {'id': '532', 'name': 'Timburr', 'number': '532'},
    {'id': '533', 'name': 'Gurdurr', 'number': '533'},
    {'id': '534', 'name': 'Conkeldurr', 'number': '534'},
    {'id': '535', 'name': 'Tympole', 'number': '535'},
    {'id': '536', 'name': 'Palpitoad', 'number': '536'},
    {'id': '537', 'name': 'Seismitoad', 'number': '537'},
    {'id': '538', 'name': 'Throh', 'number': '538'},
    {'id': '539', 'name': 'Sawk', 'number': '539'},
    {'id': '540', 'name': 'Sewaddle', 'number': '540'},
    {'id': '541', 'name': 'Swadloon', 'number': '541'},
    {'id': '542', 'name': 'Leavanny', 'number': '542'},
    {'id': '543', 'name': 'Venipede', 'number': '543'},
    {'id': '544', 'name': 'Whirlipede', 'number': '544'},
    {'id': '545', 'name': 'Scolipede', 'number': '545'},
    {'id': '546', 'name': 'Cottonee', 'number': '546'},
    {'id': '547', 'name': 'Whimsicott', 'number': '547'},
    {'id': '548', 'name': 'Petilil', 'number': '548'},
    {'id': '549', 'name': 'Lilligant', 'number': '549'},
    {'id': '550', 'name': 'Basculin (Both Froms)', 'number': '550'},
    {'id': 'basculin-red', 'name': 'Basculin (Red-Striped Form)', 'number': '550'},
    {'id': 'basculin-blue', 'name': 'Basculin (Blue-Striped Form)', 'number': '550'},
    {'id': '551', 'name': 'Sandile', 'number': '551'},
    {'id': '552', 'name': 'Krokorok', 'number': '552'},
    {'id': '553', 'name': 'Krookodile', 'number': '553'},
    {'id': '554', 'name': 'Darumaka', 'number': '554'},
    {'id': '555', 'name': 'Darmanitan (Standard Mode)', 'number': '555'},
    {'id': 'darmanitan-zen', 'name': 'Darmanitan (Zen Mode)', 'number': '555'},
    {'id': '556', 'name': 'Maractus', 'number': '556'},
    {'id': '557', 'name': 'Dwebble', 'number': '557'},
    {'id': '558', 'name': 'Crustle', 'number': '558'},
    {'id': '559', 'name': 'Scraggy', 'number': '559'},
    {'id': '560', 'name': 'Scrafty', 'number': '560'},
    {'id': '561', 'name': 'Sigilyph', 'number': '561'},
    {'id': '562', 'name': 'Yamask', 'number': '562'},
    {'id': '563', 'name': 'Cofagrigus', 'number': '563'},
    {'id': '564', 'name': 'Tirtouga', 'number': '564'},
    {'id': '565', 'name': 'Carracosta', 'number': '565'},
    {'id': '566', 'name': 'Archen', 'number': '566'},
    {'id': '567', 'name': 'Archeops', 'number': '567'},
    {'id': '568', 'name': 'Trubbish', 'number': '568'},
    {'id': '569', 'name': 'Garbodor', 'number': '569'},
    {'id': '570', 'name': 'Zorua', 'number': '570'},
    {'id': '571', 'name': 'Zoroark', 'number': '571'},
    {'id': '572', 'name': 'Minccino', 'number': '572'},
    {'id': '573', 'name': 'Cinccino', 'number': '573'},
    {'id': '574', 'name': 'Gothita', 'number': '574'},
    {'id': '575', 'name': 'Gothorita', 'number': '575'},
    {'id': '576', 'name': 'Gothitelle', 'number': '576'},
    {'id': '577', 'name': 'Solosis', 'number': '577'},
    {'id': '578', 'name': 'Duosion', 'number': '578'},
    {'id': '579', 'name': 'Reuniclus', 'number': '579'},
    {'id': '580', 'name': 'Ducklett', 'number': '580'},
    {'id': '581', 'name': 'Swanna', 'number': '581'},
    {'id': '582', 'name': 'Vanillite', 'number': '582'},
    {'id': '583', 'name': 'Vanillish', 'number': '583'},
    {'id': '584', 'name': 'Vanilluxe', 'number': '584'},
    {'id': 'deerling-spring', 'name': 'Deerling (Spring Form)', 'number': '585'},
    {'id': 'deerling-autumn', 'name': 'Deerling (Autumn Form)', 'number': '585'},
    {'id': 'deerling-summer', 'name': 'Deerling (Summer Form)', 'number': '585'},
    {'id': 'deerling-winter', 'name': 'Deerling (Winter Form)', 'number': '585'},
    {'id': 'sawsbuck-spring', 'name': 'Sawsbuck (Spring Form)', 'number': '586'},
    {'id': 'sawsbuck-autumn', 'name': 'Sawsbuck (Autumn Form)', 'number': '586'},
    {'id': 'sawsbuck-summer', 'name': 'Sawsbuck (Summer Form)', 'number': '586'},
    {'id': 'sawsbuck-winter', 'name': 'Sawsbuck (Winter Form)', 'number': '586'},
    {'id': '587', 'name': 'Emolga', 'number': '587'},
    {'id': '588', 'name': 'Karrablast', 'number': '588'},
    {'id': '589', 'name': 'Escavalier', 'number': '589'},
    {'id': '590', 'name': 'Foongus', 'number': '590'},
    {'id': '591', 'name': 'Amoonguss', 'number': '591'},
    {'id': '592', 'name': 'Frillish (Both)', 'number': '592'},
    {'id': 'frillish-male', 'name': 'Frillish (Male)', 'number': '592'},
    {'id': 'frillish-female', 'name': 'Frillish (Female)', 'number': '592'},
    {'id': '593', 'name': 'Jellicent (Both)', 'number': '593'},
    {'id': 'jellicent-male', 'name': 'Jellicent (Male)', 'number': '593'},
    {'id': 'jellicent-female', 'name': 'Jellicent (Female)', 'number': '593'},
    {'id': '594', 'name': 'Alomomola', 'number': '594'},
    {'id': '595', 'name': 'Joltik', 'number': '595'},
    {'id': '596', 'name': 'Galvantula', 'number': '596'},
    {'id': '597', 'name': 'Ferroseed', 'number': '597'},
    {'id': '598', 'name': 'Ferrothorn', 'number': '598'},
    {'id': '599', 'name': 'Klink', 'number': '599'},
    {'id': '600', 'name': 'Klang', 'number': '600'},
    {'id': '601', 'name': 'Klinklang', 'number': '601'},
    {'id': '602', 'name': 'Tynamo', 'number': '602'},
    {'id': '603', 'name': 'Eelektrik', 'number': '603'},
    {'id': '604', 'name': 'Eelektross', 'number': '604'},
    {'id': '605', 'name': 'Elgyem', 'number': '605'},
    {'id': '606', 'name': 'Beheeyem', 'number': '606'},
    {'id': '607', 'name': 'Litwick', 'number': '607'},
    {'id': '608', 'name': 'Lampent', 'number': '608'},
    {'id': '609', 'name': 'Chandelure', 'number': '609'},
    {'id': '610', 'name': 'Axew', 'number': '610'},
    {'id': '611', 'name': 'Fraxure', 'number': '611'},
    {'id': '612', 'name': 'Haxorus', 'number': '612'},
    {'id': '613', 'name': 'Cubchoo', 'number': '613'},
    {'id': '614', 'name': 'Beartic', 'number': '614'},
    {'id': '615', 'name': 'Cryogonal', 'number': '615'},
    {'id': '616', 'name': 'Shelmet', 'number': '616'},
    {'id': '617', 'name': 'Accelgor', 'number': '617'},
    {'id': '618', 'name': 'Stunfisk', 'number': '618'},
    {'id': '619', 'name': 'Mienfoo', 'number': '619'},
    {'id': '620', 'name': 'Mienshao', 'number': '620'},
    {'id': '621', 'name': 'Druddigon', 'number': '621'},
    {'id': '622', 'name': 'Golett', 'number': '622'},
    {'id': '623', 'name': 'Golurk', 'number': '623'},
    {'id': '624', 'name': 'Pawniard', 'number': '624'},
    {'id': '625', 'name': 'Bisharp', 'number': '625'},
    {'id': '626', 'name': 'Bouffalant', 'number': '626'},
    {'id': '627', 'name': 'Rufflet', 'number': '627'},
    {'id': '628', 'name': 'Braviary', 'number': '628'},
    {'id': '629', 'name': 'Vullaby', 'number': '629'},
    {'id': '630', 'name': 'Mandibuzz', 'number': '630'},
    {'id': '631', 'name': 'Heatmor', 'number': '631'},
    {'id': '632', 'name': 'Durant', 'number': '632'},
    {'id': '633', 'name': 'Deino', 'number': '633'},
    {'id': '634', 'name': 'Zweilous', 'number': '634'},
    {'id': '635', 'name': 'Hydreigon', 'number': '635'},
    {'id': '636', 'name': 'Larvesta', 'number': '636'},
    {'id': '637', 'name': 'Volcarona', 'number': '637'},
    {'id': '638', 'name': 'Cobalion', 'number': '638'},
    {'id': '639', 'name': 'Terrakion', 'number': '639'},
    {'id': '640', 'name': 'Virizion', 'number': '640'},
    {'id': 'tornadus-incarnate', 'name': 'Tornadus (Incarnate Forme)', 'number': '641'},
    {'id': 'tornadus-therian', 'name': 'Tornadus (Therian Forme)', 'number': '641'},
    {'id': 'thundurus-incarnate', 'name': 'Thundurus (Incarnate Forme)', 'number': '642'},
    {'id': 'thundurus-therian', 'name': 'Thundurus (Therian Forme)', 'number': '642'},
    {'id': '643', 'name': 'Reshiram', 'number': '643'},
    {'id': '644', 'name': 'Zekrom', 'number': '644'},
    {'id': 'landorus-incarnate', 'name': 'Landorus (Incarnate Forme)', 'number': '645'},
    {'id': 'landorus-therian', 'name': 'Landorus (Therian Forme)', 'number': '645'},
    {'id': '646', 'name': 'Kyurem', 'number': '646'},
    {'id': 'kyurem-black', 'name': 'Black Kyurem', 'number': '646'},
    {'id': 'kyurem-white', 'name': 'White Kyurem', 'number': '646'},
    {'id': '647', 'name': 'Keldeo (Ordinary Form)', 'number': '647'},
    {'id': 'keldeo-resolute', 'name': 'Keldeo (Resolute Form)', 'number': '647'},
    {'id': 'meloetta-aria', 'name': 'Meloetta (Aria Forme)', 'number': '648'},
    {'id': 'meloetta-pirouette', 'name': 'Meloetta (Pirouette Forme)', 'number': '648'},
    {'id': '649', 'name': 'Genesect (Normal)', 'number': '649'},
    {'id': 'genesect-burn', 'name': 'Genesect (Burn Drive)', 'number': '649'},
    {'id': 'genesect-chill', 'name': 'Genesect (Chill Drive)', 'number': '649'},
    {'id': 'genesect-douse', 'name': 'Genesect (Douse Drive)', 'number': '649'},
    {'id': 'genesect-shock', 'name': 'Genesect (Shock Drive)', 'number': '649'},
]

# https://bulbapedia.bulbagarden.net/wiki/Mega_Evolution#Pok.C3.A9mon_capable_of_Mega_Evolution
KALOS_MEGA = [
    {'id': 'venusaur-mega', 'name': 'Mega Venusaur', 'number': '3'},
    {'id': 'charizard-mega-x', 'name': 'Mega Charizard X', 'number': '6'},
    {'id': 'charizard-mega-y', 'name': 'Mega Charizard Y', 'number': '6'},
    {'id': 'blastoise-mega', 'name': 'Mega Blastoise', 'number': '9'},
    {'id': 'beedrill-mega', 'name': 'Mega Beedrill', 'number': '15'},
    {'id': 'pidgeot-mega', 'name': 'Mega Pidgeot', 'number': '18'},
    {'id': 'alakazam-mega', 'name': 'Mega Alakazam', 'number': '65'},
    {'id': 'slowbro-mega', 'name': 'Mega Slowbro', 'number': '80'},
    {'id': 'gengar-mega', 'name': 'Mega Gengar', 'number': '94'},
    {'id': 'kangaskhan-mega', 'name': 'Mega Kangaskhan', 'number': '115'},
    {'id': 'pinsir-mega', 'name': 'Mega Pinsir', 'number': '127'},
    {'id': 'gyarados-mega', 'name': 'Mega Gyarados', 'number': '130'},
    {'id': 'aerodactyl-mega', 'name': 'Mega Aerodactyl', 'number': '142'},
    {'id': 'mewtwo-mega-x', 'name': 'Mega Mewtwo X', 'number': '150'},
    {'id': 'mewtwo-mega-y', 'name': 'Mega Mewtwo Y', 'number': '150'},
    {'id': 'ampharos-mega', 'name': 'Mega Ampharos', 'number': '181'},
    {'id': 'steelix-mega', 'name': 'Mega Steelix', 'number': '208'},
    {'id': 'scizor-mega', 'name': 'Mega Scizor', 'number': '212'},
    {'id': 'heracross-mega', 'name': 'Mega Heracross', 'number': '214'},
    {'id': 'houndoom-mega', 'name': 'Mega Houndoom', 'number': '229'},
    {'id': 'tyranitar-mega', 'name': 'Mega Tyranitar', 'number': '248'},
    {'id': 'sceptile-mega', 'name': 'Mega Sceptile', 'number': '254'},
    {'id': 'blaziken-mega', 'name': 'Mega Blaziken', 'number': '257'},
    {'id': 'swampert-mega', 'name': 'Mega Swampert', 'number': '260'},
    {'id': 'gardevoir-mega', 'name': 'Mega Gardevoir', 'number': '282'},
    {'id': 'sableye-mega', 'name': 'Mega Sableye', 'number': '302'},
    {'id': 'mawile-mega', 'name': 'Mega Mawile', 'number': '303'},
    {'id': 'aggron-mega', 'name': 'Mega Aggron', 'number': '306'},
    {'id': 'medicham-mega', 'name': 'Mega Medicham', 'number': '308'},
    {'id': 'manectric-mega', 'name': 'Mega Manectric', 'number': '310'},
    {'id': 'sharpedo-mega', 'name': 'Mega Sharpedo', 'number': '319'},
    {'id': 'camerupt-mega', 'name': 'Mega Camerupt', 'number': '323'},
    {'id': 'altaria-mega', 'name': 'Mega Altaria', 'number': '334'},
    {'id': 'banette-mega', 'name': 'Mega Banette', 'number': '354'},
    {'id': 'absol-mega', 'name': 'Mega Absol', 'number': '359'},
    {'id': 'glalie-mega', 'name': 'Mega Glalie', 'number': '362'},
    {'id': 'salamence-mega', 'name': 'Mega Salamence', 'number': '373'},
    {'id': 'metagross-mega', 'name': 'Mega Metagross', 'number': '376'},
    {'id': 'latias-mega', 'name': 'Mega Latias', 'number': '380'},
    {'id': 'latios-mega', 'name': 'Mega Latios', 'number': '381'},
    {'id': 'rayquaza-mega', 'name': 'Mega Rayquaza', 'number': '384'},
    {'id': 'lopunny-mega', 'name': 'Mega Lopunny', 'number': '428'},
    {'id': 'garchomp-mega', 'name': 'Mega Garchomp', 'number': '445'},
    {'id': 'lucario-mega', 'name': 'Mega Lucario', 'number': '448'},
    {'id': 'abomasnow-mega', 'name': 'Mega Abomasnow', 'number': '460'},
    {'id': 'gallade-mega', 'name': 'Mega Gallade', 'number': '475'},
    {'id': 'audino-mega', 'name': 'Mega Audino', 'number': '531'},
    {'id': 'diancie-mega', 'name': 'Mega Diancie', 'number': '719'},
]

# https://bulbapedia.bulbagarden.net/wiki/Primal_Reversion#Pok.C3.A9mon_capable_of_Primal_Reversion
KALOS_PRIMAL_REVERSION = [
    {'id': 'kyogre-primal', 'name': 'Primal Kyogre', 'number': '382'},
    {'id': 'groudon-primal', 'name': 'Primal Groudon', 'number': '383'},
]

KALOS = [
    {'id': '650', 'name': 'Chespin', 'number': '650'},
    {'id': '651', 'name': 'Quilladin', 'number': '651'},
    {'id': '652', 'name': 'Chesnaught', 'number': '652'},
    {'id': '653', 'name': 'Fennekin', 'number': '653'},
    {'id': '654', 'name': 'Braixen', 'number': '654'},
    {'id': '655', 'name': 'Delphox', 'number': '655'},
    {'id': '656', 'name': 'Froakie', 'number': '656'},
    {'id': '657', 'name': 'Frogadier', 'number': '657'},
    {'id': '658', 'name': 'Greninja', 'number': '658'},
    {'id': 'greninja-ash', 'name': 'Ash-Greninja', 'number': '658'},
    {'id': '659', 'name': 'Bunnelby', 'number': '659'},
    {'id': '660', 'name': 'Diggersby', 'number': '660'},
    {'id': '661', 'name': 'Fletchling', 'number': '661'},
    {'id': '662', 'name': 'Fletchinder', 'number': '662'},
    {'id': '663', 'name': 'Talonflame', 'number': '663'},
    {'id': '664', 'name': 'Scatterbug', 'number': '664'},
    {'id': '665', 'name': 'Spewpa', 'number': '665'},
    {'id': 'vivillon-archipelago', 'name': 'Vivillon (Archipelago Pattern)', 'number': '666'},
    {'id': 'vivillon-continental', 'name': 'Vivillon (Continental Pattern)', 'number': '666'},
    {'id': 'vivillon-elegant', 'name': 'Vivillon (Elegant Pattern)', 'number': '666'},
    {'id': 'vivillon-garden', 'name': 'Vivillon (Garden Pattern)', 'number': '666'},
    {'id': 'vivillon-high', 'name': 'Vivillon (High Plains Pattern)', 'number': '666'},
    {'id': 'vivillon-icy', 'name': 'Vivillon (Icy Snow Pattern)', 'number': '666'},
    {'id': 'vivillon-jungle', 'name': 'Vivillon (Jungle Pattern)', 'number': '666'},
    {'id': 'vivillon-marine', 'name': 'Vivillon (Marine Pattern)', 'number': '666'},
    {'id': 'vivillon-meadow', 'name': 'Vivillon (Meadow Pattern)', 'number': '666'},
    {'id': 'vivillon-modern', 'name': 'Vivillon (Modern Pattern)', 'number': '666'},
    {'id': 'vivillon-monsoon', 'name': 'Vivillon (Monsoon Pattern)', 'number': '666'},
    {'id': 'vivillon-ocean', 'name': 'Vivillon (Ocean Pattern)', 'number': '666'},
    {'id': 'vivillon-polar', 'name': 'Vivillon (Polar Pattern)', 'number': '666'},
    {'id': 'vivillon-river', 'name': 'Vivillon (River Pattern)', 'number': '666'},
    {'id': 'vivillon-sandstorm', 'name': 'Vivillon (Sandstorm Pattern)', 'number': '666'},
    {'id': 'vivillon-savanna', 'name': 'Vivillon (Savanna Pattern)', 'number': '666'},
    {'id': 'vivillon-sun', 'name': 'Vivillon (Sun Pattern)', 'number': '666'},
    {'id': 'vivillon-tundra', 'name': 'Vivillon (Tundra Pattern)', 'number': '666'},
    {'id': '667', 'name': 'Litleo', 'number': '667'},
    {'id': '668', 'name': 'Pyroar (Both)', 'number': '668'},
    {'id': 'pyroar-male', 'name': 'Pyroar (Male)', 'number': '668'},
    {'id': 'pyroar-female', 'name': 'Pyroar (Female)', 'number': '668'},
    {'id': '669', 'name': 'Flabébé', 'number': '669'},
    {'id': '670', 'name': 'Floette', 'number': '670'},
    {'id': '671', 'name': 'Florges', 'number': '671'},
    {'id': '672', 'name': 'Skiddo', 'number': '672'},
    {'id': '673', 'name': 'Gogoat', 'number': '673'},
    {'id': '674', 'name': 'Pancham', 'number': '674'},
    {'id': '675', 'name': 'Pangoro', 'number': '675'},
    {'id': '676', 'name': 'Furfrou (Natural Trim)', 'number': '676'},
    {'id': 'furfrou-dandy', 'name': 'Furfrou (Dandy Trim)', 'number': '676'},
    {'id': 'furfrou-debutante', 'name': 'Furfrou (Debutante Trim)', 'number': '676'},
    {'id': 'furfrou-diamond', 'name': 'Furfrou (Diamond Trim)', 'number': '676'},
    {'id': 'furfrou-heart', 'name': 'Furfrou (Heart Trim)', 'number': '676'},
    {'id': 'furfrou-kabuki', 'name': 'Furfrou (Kabuki Trim)', 'number': '676'},
    {'id': 'furfrou-la-reine', 'name': 'Furfrou (La Reine Trim)', 'number': '676'},
    {'id': 'furfrou-matron', 'name': 'Furfrou (Matron Trim)', 'number': '676'},
    {'id': 'furfrou-pharaoh', 'name': 'Furfrou (Pharaoh Trim)', 'number': '676'},
    {'id': 'furfrou-star', 'name': 'Furfrou (Star Trim)', 'number': '676'},
    {'id': '677', 'name': 'Espurr', 'number': '677'},
    {'id': '678', 'name': 'Meowstic (Both)', 'number': '678'},
    {'id': 'meowstic-male', 'name': 'Meowstic (Male)', 'number': '678'},
    {'id': 'meowstic-female', 'name': 'Meowstic (Female)', 'number': '678'},
    {'id': '679', 'name': 'Honedge', 'number': '679'},
    {'id': '680', 'name': 'Doublade', 'number': '680'},
    {'id': '681', 'name': 'Aegislash (Both)', 'number': '681'},
    {'id': 'aegislash-blade', 'name': 'Aegislash (Blade Forme)', 'number': '681'},
    {'id': 'aegislash-shield', 'name': 'Aegislash (Shield Forme)', 'number': '681'},
    {'id': '682', 'name': 'Spritzee', 'number': '682'},
    {'id': '683', 'name': 'Aromatisse', 'number': '683'},
    {'id': '684', 'name': 'Swirlix', 'number': '684'},
    {'id': '685', 'name': 'Slurpuff', 'number': '685'},
    {'id': '686', 'name': 'Inkay', 'number': '686'},
    {'id': '687', 'name': 'Malamar', 'number': '687'},
    {'id': '688', 'name': 'Binacle', 'number': '688'},
    {'id': '689', 'name': 'Barbaracle', 'number': '689'},
    {'id': '690', 'name': 'Skrelp', 'number': '690'},
    {'id': '691', 'name': 'Dragalge', 'number': '691'},
    {'id': '692', 'name': 'Clauncher', 'number': '692'},
    {'id': '693', 'name': 'Clawitzer', 'number': '693'},
    {'id': '694', 'name': 'Helioptile', 'number': '694'},
    {'id': '695', 'name': 'Heliolisk', 'number': '695'},
    {'id': '696', 'name': 'Tyrunt', 'number': '696'},
    {'id': '697', 'name': 'Tyrantrum', 'number': '697'},
    {'id': '698', 'name': 'Amaura', 'number': '698'},
    {'id': '699', 'name': 'Aurorus', 'number': '699'},
    {'id': '700', 'name': 'Sylveon', 'number': '700'},
    {'id': '701', 'name': 'Hawlucha', 'number': '701'},
    {'id': '702', 'name': 'Dedenne', 'number': '702'},
    {'id': '703', 'name': 'Carbink', 'number': '703'},
    {'id': '704', 'name': 'Goomy', 'number': '704'},
    {'id': '705', 'name': 'Sliggoo', 'number': '705'},
    {'id': '706', 'name': 'Goodra', 'number': '706'},
    {'id': '707', 'name': 'Klefki', 'number': '707'},
    {'id': '708', 'name': 'Phantump', 'number': '708'},
    {'id': '709', 'name': 'Trevenant', 'number': '709'},
    {'id': 'pumpkaboo-average', 'name': 'Pumpkaboo (Average Size)', 'number': '710'},
    {'id': 'pumpkaboo-large', 'name': 'Pumpkaboo (Large Size)', 'number': '710'},
    {'id': 'pumpkaboo-small', 'name': 'Pumpkaboo (Small Size)', 'number': '710'},
    {'id': 'pumpkaboo-super', 'name': 'Pumpkaboo (Super Size)', 'number': '710'},
    {'id': 'gourgeist-average', 'name': 'Gourgeist (Average Size)', 'number': '711'},
    {'id': 'gourgeist-large', 'name': 'Gourgeist (Large Size)', 'number': '711'},
    {'id': 'gourgeist-small', 'name': 'Gourgeist (Small Size)', 'number': '711'},
    {'id': 'gourgeist-super', 'name': 'Gourgeist (Super Size)', 'number': '711'},
    {'id': '712', 'name': 'Bergmite', 'number': '712'},
    {'id': '713', 'name': 'Avalugg', 'number': '713'},
    {'id': '714', 'name': 'Noibat', 'number': '714'},
    {'id': '715', 'name': 'Noivern', 'number': '715'},
    {'id': '716', 'name': 'Xerneas', 'number': '716'},
    {'id': '717', 'name': 'Yveltal', 'number': '717'},
    {'id': '718', 'name': 'Zygarde (50% Forme)', 'number': '718'},
    {'id': 'zygarde-10', 'name': 'Zygarde (10% Forme)', 'number': '718'},
    {'id': 'zygarde-complete', 'name': 'Zygarde (Complete Forme)', 'number': '718'},
    {'id': '719', 'name': 'Diancie', 'number': '719'},
    {'id': 'hoopa-confined', 'name': 'Hoopa (Confined)', 'number': '720'},
    {'id': 'hoopa-unbound', 'name': 'Hoopa (Unbound)', 'number': '720'},
    {'id': '721', 'name': 'Volcanion', 'number': '721'},
]

# https://bulbapedia.bulbagarden.net/wiki/Regional_form#List_of_Alolan_Forms
ALOLA_FORMS = [
    {'id': 'rattata-alola', 'name': 'Alolan Rattata', 'number': '19'},
    {'id': 'raticate-alola', 'name': 'Alolan Raticate', 'number': '20'},
    {'id': 'raichu-alola', 'name': 'Alolan Raichu', 'number': '26'},
    {'id': 'sandshrew-alola', 'name': 'Alolan Sandshrew', 'number': '27'},
    {'id': 'sandslash-alola', 'name': 'Alolan Sandslash', 'number': '28'},
    {'id': 'vulpix-alola', 'name': 'Alolan Vulpix', 'number': '37'},
    {'id': 'ninetales-alola', 'name': 'Alolan Ninetales', 'number': '38'},
    {'id': 'diglett-alola', 'name': 'Alolan Diglett', 'number': '50'},
    {'id': 'dugtrio-alola', 'name': 'Alolan Dugtrio', 'number': '51'},
    {'id': 'meowth-alola', 'name': 'Alolan Meowth', 'number': '52'},
    {'id': 'persian-alola', 'name': 'Alolan Persian', 'number': '53'},
    {'id': 'geodude-alola', 'name': 'Alolan Geodude', 'number': '74'},
    {'id': 'graveler-alola', 'name': 'Alolan Graveler', 'number': '75'},
    {'id': 'golem-alola', 'name': 'Alolan Golem', 'number': '76'},
    {'id': 'grimer-alola', 'name': 'Alolan Grimer', 'number': '88'},
    {'id': 'muk-alola', 'name': 'Alolan Muk', 'number': '89'},
    {'id': 'exeggutor-alola', 'name': 'Alolan Exeggutor', 'number': '103'},
    {'id': 'marowak-alola', 'name': 'Alolan Marowak', 'number': '105'},
]

ALOLA = [
    {'id': '722', 'name': 'Rowlet', 'number': '722'},
    {'id': '723', 'name': 'Dartrix', 'number': '723'},
    {'id': '724', 'name': 'Decidueye', 'number': '724'},
    {'id': '725', 'name': 'Litten', 'number': '725'},
    {'id': '726', 'name': 'Torracat', 'number': '726'},
    {'id': '727', 'name': 'Incineroar', 'number': '727'},
    {'id': '728', 'name': 'Popplio', 'number': '728'},
    {'id': '729', 'name': 'Brionne', 'number': '729'},
    {'id': '730', 'name': 'Primarina', 'number': '730'},
    {'id': '731', 'name': 'Pikipek', 'number': '731'},
    {'id': '732', 'name': 'Trumbeak', 'number': '732'},
    {'id': '733', 'name': 'Toucannon', 'number': '733'},
    {'id': '734', 'name': 'Yungoos', 'number': '734'},
    {'id': '735', 'name': 'Gumshoos', 'number': '735'},
    {'id': '736', 'name': 'Grubbin', 'number': '736'},
    {'id': '737', 'name': 'Charjabug', 'number': '737'},
    {'id': '738', 'name': 'Vikavolt', 'number': '738'},
    {'id': '739', 'name': 'Crabrawler', 'number': '739'},
    {'id': '740', 'name': 'Crabominable', 'number': '740'},
    {'id': 'oricorio-baile', 'name': 'Oricorio (Baile Style)', 'number': '741'},
    {'id': 'oricorio-pom-pom', 'name': 'Oricorio (Pom-Pom Style)', 'number': '741'},
    {'id': "oricorio-pa'u", 'name': "Oricorio (Pa'u Style)", 'number': '741'},
    {'id': 'oricorio-sensu', 'name': 'Oricorio (Sensu Style)', 'number': '741'},
    {'id': '742', 'name': 'Cutiefly', 'number': '742'},
    {'id': '743', 'name': 'Ribombee', 'number': '743'},
    {'id': '744', 'name': 'Rockruff', 'number': '744'},
    {'id': '745', 'name': 'Lycanroc (Midday Form)', 'number': '745'},
    {'id': 'lycanroc-dusk', 'name': 'Lycanroc (Dusk Form)', 'number': '745'},
    {'id': 'lycanroc-midnight', 'name': 'Lycanroc (Midnight Form)', 'number': '745'},
    {'id': 'wishiwashi-solo', 'name': 'Wishiwashi (Solo Form)', 'number': '746'},
    {'id': 'wishiwashi-school', 'name': 'Wishiwashi (School Form)', 'number': '746'},
    {'id': '747', 'name': 'Mareanie', 'number': '747'},
    {'id': '748', 'name': 'Toxapex', 'number': '748'},
    {'id': '749', 'name': 'Mudbray', 'number': '749'},
    {'id': '750', 'name': 'Mudsdale', 'number': '750'},
    {'id': '751', 'name': 'Dewpider', 'number': '751'},
    {'id': '752', 'name': 'Araquanid', 'number': '752'},
    {'id': '753', 'name': 'Fomantis', 'number': '753'},
    {'id': '754', 'name': 'Lurantis', 'number': '754'},
    {'id': '755', 'name': 'Morelull', 'number': '755'},
    {'id': '756', 'name': 'Shiinotic', 'number': '756'},
    {'id': '757', 'name': 'Salandit', 'number': '757'},
    {'id': '758', 'name': 'Salazzle', 'number': '758'},
    {'id': '759', 'name': 'Stufful', 'number': '759'},
    {'id': '760', 'name': 'Bewear', 'number': '760'},
    {'id': '761', 'name': 'Bounsweet', 'number': '761'},
    {'id': '762', 'name': 'Steenee', 'number': '762'},
    {'id': '763', 'name': 'Tsareena', 'number': '763'},
    {'id': '764', 'name': 'Comfey', 'number': '764'},
    {'id': '765', 'name': 'Oranguru', 'number': '765'},
    {'id': '766', 'name': 'Passimian', 'number': '766'},
    {'id': '767', 'name': 'Wimpod', 'number': '767'},
    {'id': '768', 'name': 'Golisopod', 'number': '768'},
    {'id': '769', 'name': 'Sandygast', 'number': '769'},
    {'id': '770', 'name': 'Palossand', 'number': '770'},
    {'id': '771', 'name': 'Pyukumuku', 'number': '771'},
    {'id': '772', 'name': 'Type: Null', 'number': '772'},
    {'id': '773', 'name': 'Silvally', 'number': '773'},
    {'id': '774', 'name': 'Minior (Meteor Form)', 'number': '774'},
    {'id': 'minior-core', 'name': 'Minior (Core)', 'number': '774'},
    {'id': '775', 'name': 'Komala', 'number': '775'},
    {'id': '776', 'name': 'Turtonator', 'number': '776'},
    {'id': '777', 'name': 'Togedemaru', 'number': '777'},
    {'id': '778', 'name': 'Mimikyu', 'number': '778'},
    {'id': '779', 'name': 'Bruxish', 'number': '779'},
    {'id': '780', 'name': 'Drampa', 'number': '780'},
    {'id': '781', 'name': 'Dhelmise', 'number': '781'},
    {'id': '782', 'name': 'Jangmo-o', 'number': '782'},
    {'id': '783', 'name': 'Hakamo-o', 'number': '783'},
    {'id': '784', 'name': 'Kommo-o', 'number': '784'},
    {'id': '785', 'name': 'Tapu Koko', 'number': '785'},
    {'id': '786', 'name': 'Tapu Lele', 'number': '786'},
    {'id': '787', 'name': 'Tapu Bulu', 'number': '787'},
    {'id': '788', 'name': 'Tapu Fini', 'number': '788'},
    {'id': '789', 'name': 'Cosmog', 'number': '789'},
    {'id': '790', 'name': 'Cosmoem', 'number': '790'},
    {'id': '791', 'name': 'Solgaleo', 'number': '791'},
    {'id': '792', 'name': 'Lunala', 'number': '792'},
    {'id': '793', 'name': 'Nihilego', 'number': '793'},
    {'id': '794', 'name': 'Buzzwole', 'number': '794'},
    {'id': '795', 'name': 'Pheromosa', 'number': '795'},
    {'id': '796', 'name': 'Xurkitree', 'number': '796'},
    {'id': '797', 'name': 'Celesteela', 'number': '797'},
    {'id': '798', 'name': 'Kartana', 'number': '798'},
    {'id': '799', 'name': 'Guzzlord', 'number': '799'},
    {'id': '800', 'name': 'Necrozma', 'number': '800'},
    {'id': 'necrozma-dawn', 'name': 'Dawn Wings Necrozma', 'number': '800'},
    {'id': 'necrozma-dusk', 'name': 'Dusk Mane Necrozma', 'number': '800'},
    {'id': 'necrozma-ultra', 'name': 'Ultra Necrozma', 'number': '800'},
    {'id': '801', 'name': 'Magearna', 'number': '801'},
    {'id': '802', 'name': 'Marshadow', 'number': '802'},
    {'id': '803', 'name': 'Poipole', 'number': '803'},
    {'id': '804', 'name': 'Naganadel', 'number': '804'},
    {'id': '805', 'name': 'Stakataka', 'number': '805'},
    {'id': '806', 'name': 'Blacephalon', 'number': '806'},
    {'id': '807', 'name': 'Zeraora', 'number': '807'},
    {'id': '808', 'name': 'Meltan', 'number': '808'},
    {'id': '809', 'name': 'Melmetal', 'number': '809'},
]

# https://bulbapedia.bulbagarden.net/wiki/Regional_form#List_of_Galarian_Forms
GALAR_FORMS = [
    {'id': 'meowth-galar', 'name': 'Galarian Meowth', 'number': '52'},
    {'id': 'ponyta-galar', 'name': 'Galarian Ponyta', 'number': '77'},
    {'id': 'rapidash-galar', 'name': 'Galarian Rapidash', 'number': '78'},
    {'id': 'slowpoke-galar', 'name': 'Galarian Slowpoke', 'number': '79'},
    {'id': 'slowbro-galar', 'name': 'Galarian Slowbro', 'number': '80'},
    {'id': 'farfetchd-galar', 'name': "Galarian Farfetch'd", 'number': '83'},
    {'id': 'weezing-galar', 'name': 'Galarian Weezing', 'number': '110'},
    {'id': 'mr-mime-galar', 'name': 'Galarian Mr. Mime', 'number': '122'},
    {'id': 'articuno-galar', 'name': 'Galarian Articuno', 'number': '144'},
    {'id': 'zapdos-galar', 'name': 'Galarian Zapdos', 'number': '145'},
    {'id': 'moltres-galar', 'name': 'Galarian Moltres', 'number': '146'},
    {'id': 'slowking-galar', 'name': 'Galarian Slowking', 'number': '199'},
    {'id': 'corsola-galar', 'name': 'Galarian Corsola', 'number': '222'},
    {'id': 'zigzagoon-galar', 'name': 'Galarian Zigzagoon', 'number': '263'},
    {'id': 'linoone-galar', 'name': 'Galarian Linoone', 'number': '264'},
    {'id': 'darumaka-galar', 'name': 'Galarian Darumaka', 'number': '554'},
    {'id': 'darmanitan-galar', 'name': 'Galarian Darmanitan (Standard Mode)', 'number': '555'},
    {'id': 'darmanitan-zen-galar', 'name': 'Galarian Darmanitan (Zen Mode)', 'number': '555'},
    {'id': 'yamask-galar', 'name': 'Galarian Yamask', 'number': '562'},
    {'id': 'stunfisk-galar', 'name': 'Galarian Stunfisk', 'number': '618'},
]

# https://bulbapedia.bulbagarden.net/wiki/Gigantamax#Gigantamax_Pok.C3.A9mon
GALAR_GIGANTAMAX = [
    {'id': 'venusaur-gigantamax', 'name': 'Gigantamax Venusaur', 'number': '3'},
    {'id': 'charizard-gigantamax', 'name': 'Gigantamax Charizard', 'number': '6'},
    {'id': 'blastoise-gigantamax', 'name': 'Gigantamax Blastoise', 'number': '9'},
    {'id': 'butterfree-gigantamax', 'name': 'Gigantamax Butterfree', 'number': '12'},
    {'id': 'pikachu-gigantamax', 'name': 'Gigantamax Pikachu', 'number': '25'},
    {'id': 'meowth-gigantamax', 'name': 'Gigantamax Meowth', 'number': '52'},
    {'id': 'machamp-gigantamax', 'name': 'Gigantamax Machamp', 'number': '68'},
    {'id': 'gengar-gigantamax', 'name': 'Gigantamax Gengar', 'number': '94'},
    {'id': 'kingler-gigantamax', 'name': 'Gigantamax Kingler', 'number': '99'},
    {'id': 'lapras-gigantamax', 'name': 'Gigantamax Lapras', 'number': '131'},
    {'id': 'eevee-gigantamax', 'name': 'Gigantamax Eevee', 'number': '133'},
    {'id': 'snorlax-gigantamax', 'name': 'Gigantamax Snorlax', 'number': '143'},
    {'id': 'garbodor-gigantamax', 'name': 'Gigantamax Garbodor', 'number': '569'},
    {'id': 'melmetal-gigantamax', 'name': 'Gigantamax Melmetal', 'number': '809'},
    {'id': 'rillaboom-gigantamax', 'name': 'Gigantamax Rillaboom', 'number': '812'},
    {'id': 'cinderace-gigantamax', 'name': 'Gigantamax Cinderace', 'number': '815'},
    {'id': 'inteleon-gigantamax', 'name': 'Gigantamax Inteleon', 'number': '818'},
    {'id': 'corviknight-gigantamax', 'name': 'Gigantamax Corviknight', 'number': '823'},
    {'id': 'orbeetle-gigantamax', 'name': 'Gigantamax Orbeetle', 'number': '826'},
    {'id': 'drednaw-gigantamax', 'name': 'Gigantamax Drednaw', 'number': '834'},
    {'id': 'coalossal-gigantamax', 'name': 'Gigantamax Coalossal', 'number': '839'},
    {'id': 'flapple-gigantamax', 'name': 'Gigantamax Flapple', 'number': '841'},
    {'id': 'flapple-gigantamax', 'name': 'Gigantamax Appletun', 'number': '842'},
    {'id': 'sandaconda-gigantamax', 'name': 'Gigantamax Sandaconda', 'number': '844'},
    {'id': 'toxtricity-gigantamax', 'name': 'Gigantamax Toxtricity', 'number': '849'},
    {'id': 'centiskorch-gigantamax', 'name': 'Gigantamax Centiskorch', 'number': '851'},
    {'id': 'hatterene-gigantamax', 'name': 'Gigantamax Hatterene', 'number': '858'},
    {'id': 'grimmsnarl-gigantamax', 'name': 'Gigantamax Grimmsnarl', 'number': '861'},
    {'id': 'alcremie-gigantamax', 'name': 'Gigantamax Alcremie', 'number': '869'},
    {'id': 'copperajah-gigantamax', 'name': 'Gigantamax Copperajah', 'number': '879'},
    {'id': 'duraludon-gigantamax', 'name': 'Gigantamax Duraludon', 'number': '884'},
    {'id': 'urshifu-rapid-gigantamax', 'name': 'Gigantamax Urshifu (Rapid Strike Style)', 'number': '892'},
    {'id': 'urshifu-single-gigantamax', 'name': 'Gigantamax Urshifu (Single Strike Style)', 'number': '892'},
]

GALAR = [
    {'id': '810', 'name': 'Grookey', 'number': '810'},
    {'id': '811', 'name': 'Thwackey', 'number': '811'},
    {'id': '812', 'name': 'Rillaboom', 'number': '812'},
    {'id': '813', 'name': 'Scorbunny', 'number': '813'},
    {'id': '814', 'name': 'Raboot', 'number': '814'},
    {'id': '815', 'name': 'Cinderace', 'number': '815'},
    {'id': '816', 'name': 'Sobble', 'number': '816'},
    {'id': '817', 'name': 'Drizzile', 'number': '817'},
    {'id': '818', 'name': 'Inteleon', 'number': '818'},
    {'id': '819', 'name': 'Skwovet', 'number': '819'},
    {'id': '820', 'name': 'Greedent', 'number': '820'},
    {'id': '821', 'name': 'Rookidee', 'number': '821'},
    {'id': '822', 'name': 'Corvisquire', 'number': '822'},
    {'id': '823', 'name': 'Corviknight', 'number': '823'},
    {'id': '824', 'name': 'Blipbug', 'number': '824'},
    {'id': '825', 'name': 'Dottler', 'number': '825'},
    {'id': '826', 'name': 'Orbeetle', 'number': '826'},
    {'id': '827', 'name': 'Nickit', 'number': '827'},
    {'id': '828', 'name': 'Thievul', 'number': '828'},
    {'id': '829', 'name': 'Gossifleur', 'number': '829'},
    {'id': '830', 'name': 'Eldegoss', 'number': '830'},
    {'id': '831', 'name': 'Wooloo', 'number': '831'},
    {'id': '832', 'name': 'Dubwool', 'number': '832'},
    {'id': '833', 'name': 'Chewtle', 'number': '833'},
    {'id': '834', 'name': 'Drednaw', 'number': '834'},
    {'id': '835', 'name': 'Yamper', 'number': '835'},
    {'id': '836', 'name': 'Boltund', 'number': '836'},
    {'id': '837', 'name': 'Rolycoly', 'number': '837'},
    {'id': '838', 'name': 'Carkol', 'number': '838'},
    {'id': '839', 'name': 'Coalossal', 'number': '839'},
    {'id': '840', 'name': 'Applin', 'number': '840'},
    {'id': '841', 'name': 'Flapple', 'number': '841'},
    {'id': '842', 'name': 'Appletun', 'number': '842'},
    {'id': '843', 'name': 'Silicobra', 'number': '843'},
    {'id': '844', 'name': 'Sandaconda', 'number': '844'},
    {'id': '845', 'name': 'Cramorant', 'number': '845'},
    {'id': '846', 'name': 'Arrokuda', 'number': '846'},
    {'id': '847', 'name': 'Barraskewda', 'number': '847'},
    {'id': '848', 'name': 'Toxel', 'number': '848'},
    {'id': '849', 'name': 'Toxtricity (Both Forms)', 'number': '849'},
    {'id': 'toxtricity-amped', 'name': 'Toxtricity (Amped Form)', 'number': '849'},
    {'id': 'toxtricity-low', 'name': 'Toxtricity (Low Key Form)', 'number': '849'},
    {'id': '850', 'name': 'Sizzlipede', 'number': '850'},
    {'id': '851', 'name': 'Centiskorch', 'number': '851'},
    {'id': '852', 'name': 'Clobbopus', 'number': '852'},
    {'id': '853', 'name': 'Grapploct', 'number': '853'},
    {'id': '854', 'name': 'Sinistea', 'number': '854'},
    {'id': '855', 'name': 'Polteageist', 'number': '855'},
    {'id': '856', 'name': 'Hatenna', 'number': '856'},
    {'id': '857', 'name': 'Hattrem', 'number': '857'},
    {'id': '858', 'name': 'Hatterene', 'number': '858'},
    {'id': '859', 'name': 'Impidimp', 'number': '859'},
    {'id': '860', 'name': 'Morgrem', 'number': '860'},
    {'id': '861', 'name': 'Grimmsnarl', 'number': '861'},
    {'id': '862', 'name': 'Obstagoon', 'number': '862'},
    {'id': '863', 'name': 'Perrserker', 'number': '863'},
    {'id': '864', 'name': 'Cursola', 'number': '864'},
    {'id': '865', 'name': "Sirfetch'd", 'number': '865'},
    {'id': '866', 'name': 'Mr. Rime', 'number': '866'},
    {'id': '867', 'name': 'Runerigus', 'number': '867'},
    {'id': '868', 'name': 'Milcery', 'number': '868'},
    {'id': '869', 'name': 'Alcremie', 'number': '869'},
    {'id': '870', 'name': 'Falinks', 'number': '870'},
    {'id': '871', 'name': 'Pincurchin', 'number': '871'},
    {'id': '872', 'name': 'Snom', 'number': '872'},
    {'id': '873', 'name': 'Frosmoth', 'number': '873'},
    {'id': '874', 'name': 'Stonjourner', 'number': '874'},
    {'id': 'eiscue-ice', 'name': 'Eiscue (Ice Face)', 'number': '875'},
    {'id': 'eiscue-noice', 'name': 'Eiscue (Noice Face)', 'number': '875'},
    {'id': '876', 'name': 'Indeedee (Both)', 'number': '876'},
    {'id': 'indeedee-male', 'name': 'Indeedee (Male)', 'number': '876'},
    {'id': 'indeedee-female', 'name': 'Indeedee (Female)', 'number': '876'},
    {'id': '877', 'name': 'Morpeko (Both)', 'number': '877'},
    {'id': 'morpeko-full', 'name': 'Morpeko (Full Belly Mode)', 'number': '877'},
    {'id': 'morpeko-hangry', 'name': 'Morpeko (Hangry Mode)', 'number': '877'},
    {'id': '878', 'name': 'Cufant', 'number': '878'},
    {'id': '879', 'name': 'Copperajah', 'number': '879'},
    {'id': '880', 'name': 'Dracozolt', 'number': '880'},
    {'id': '881', 'name': 'Arctozolt', 'number': '881'},
    {'id': '882', 'name': 'Dracovish', 'number': '882'},
    {'id': '883', 'name': 'Arctovish', 'number': '883'},
    {'id': '884', 'name': 'Duraludon', 'number': '884'},
    {'id': '885', 'name': 'Dreepy', 'number': '885'},
    {'id': '886', 'name': 'Drakloak', 'number': '886'},
    {'id': '887', 'name': 'Dragapult', 'number': '887'},
    {'id': '888', 'name': 'Zacian (Crowned Sword)', 'number': '888'},
    {'id': 'zacian-hero', 'name': 'Zacian (Hero of Many Battles)', 'number': '888'},
    {'id': '889', 'name': 'Zamazenta (Crowned Sword)', 'number': '889'},
    {'id': 'zamazenta-hero', 'name': 'Zamazenta (Hero of Many Battles)', 'number': '889'},
    {'id': '890', 'name': 'Eternatus', 'number': '890'},
    {'id': '891', 'name': 'Kubfu', 'number': '891'},
    {'id': 'urshifu-rapid', 'name': 'Urshifu (Rapid Strike Style)', 'number': '892'},
    {'id': 'urshifu-single', 'name': 'Urshifu (Single Strike Style)', 'number': '892'},
    {'id': '893', 'name': 'Zarude', 'number': '893'},
    {'id': '894', 'name': 'Regieleki', 'number': '894'},
    {'id': '895', 'name': 'Regidrago', 'number': '895'},
    {'id': '896', 'name': 'Glastrier', 'number': '896'},
    {'id': '897', 'name': 'Spectrier', 'number': '897'},
    {'id': '898', 'name': 'Calyrex', 'number': '898'},
    {'id': 'calyrex-ice', 'name': 'Ice Rider Calyrex', 'number': '898'},
    {'id': 'calyrex-shadow', 'name': 'Shadow Rider Calyrex', 'number': '898'},
]


def get_region(region: str) -> Dict[str, List[Dict[str, str]]]:
    if region == "Kanto":
        return {"Local": KANTO}
    elif region == "Johto":
        return {"Local": JOHTO}
    elif region == "Hoenn":
        return {"Local": HOENN}
    elif region == "Sinnoh":
        return {"Local": SINNOH}
    elif region == "Unova":
        return {"Local": UNOVA}
    elif region == "Kalos":
        return {"Local": KALOS, "Mega Evolutions": KALOS_MEGA, "Primal Reversion": KALOS_PRIMAL_REVERSION}
    elif region == "Alola":
        return {"Local": ALOLA, "Alolan Forms": ALOLA_FORMS}
    elif region == "Galar":
        return {"Local": GALAR, "Galarian Forms": GALAR_FORMS, "Gigantamax Forms": GALAR_GIGANTAMAX}
    else:
        return {}
